// Seeding Instructions:
// Add a name, price, quantity, imageUrl, and sport to the END of their respective
// arrays. That process will seed 1 item
// IMPORTANT

const names = [
  'Basketball Hoop',
  'Football Helmet',
  'Football',
  'Basketball',
  'Baseball Glove',
  'Signed LeBron James Photo',
  'Signed Anderson Chan Mouse',
  'Signed Darren Hu Basketball',
  'Field Goal Posts',
  'Computer Monitor',
  'Home Plate',
  'Baseball Bat',
  'Nike Shoes',
  'Carpal Tunnel Cream',
  'Football Gloves',
  'Giants T-Shirt',
  'Jets T-Shirt',
  'Patriots T-Shirt',
  'Lakers Jersey',
  'Knicks Jersey',
  'Celtics Jersey',
  'Mets Jersey',
  'Yankees Jersey',
  'Red Sox Jersey',
  'Cavaliers Jersey',
  'Manchester United Jersey',
  'Ronaldo Jersey',
  'Messi Jersey',
  'Team USA Shirt',
  'Soccer Ball',
  'Soccer Cleats',
  'Shin Guards',
  'Goalie Gloves',
  'Real Madrid Jersey',
  'Barcelona Jersey',
  'Xbox One S',
  'Playstation 4',
  'Nintendo Switch',
  'Xbox One Controller',
  'Playstation 4 Controller',
  'Nintendo Switch Controller',
  'Fortnite V-Bucks Gift Cards',
  'Call of Duty Modern Warfare',
]

const descriptions = [
  'Materials: Made of durable polypropylene fiber material,heavy duty net for use outdoors or indoors. Length: 50cm. Basketball Net, 12 Loops Basketball Net, Heavy Duty Basketball Net, Heavy Duty Basketball Net Replacement Basketball Net for Wall Mounted Basketball Hoop Indoor Outdoor',
  'Great for autographs and collectors. Includes interior padding and a 4-point chinstrap. Approximately 5" tall',
  'Composite Leather. Imported. Official Size Football. NFL Branded. Super Grip Composite cover for a premium feel. Butyl rubber bladder for advanced air retention. Recommended for players 14+',
  'THE #1 INDOOR BALL: The Evolution is the #1 indoor game basketball in America, on more courts than any other basketball. SIGNATURE EVO FEEL: The soft feel that the Evolution basketball is famous for is due it’s Cushion Core Carcass, making the ball softer to the touch and easier to grip around the rim',
  'Easy break in: The soft synthetic leather material is lightweight and responsive making the glove easy and quick to break in so it will be game ready in no time for baseball, softball, or teeball',
]

const lorem = [
  'Lorem ipsum dolor sit amet, repudiandae philosophia instructior eam in, ut choro verterem argumentum vel, eu fugit dicant blandit usu. Congue soleat prodesset an vim, eam iudicabit inciderint at. Eam te wisi disputando delicatissimi, indoctum accusamus quaerendum duo ex. At vix veri magna constituto, cu viris lobortis eum, rebum legimus molestie sea an.',
  'Eum putant singulis ad, ex nec omnium indoctum, per exerci menandri at. Ne exerci suscipit dissentiunt pri. Ex regione omnesque insolens est, has in saperet mandamus. Usu ex alia novum. Cibo similique vix id, mundi minimum vituperatoribus ea eam, vel cibo probatus in.',
  'Lorem electram vituperata qui in. Aperiam saperet convenire qui ad. Vix et nisl labitur, no eius dissentiet pro. Ei eum accumsan patrioque consectetuer. Ea graeci fabulas est, his alia euismod alienum eu. Simul singulis ullamcorper eos an, ex summo eruditi duo. No sea meis sadipscing scribentur.',
]

let seedLimit = names.length - descriptions.length
for (let i = 0; i < seedLimit; i++) {
  let loremIndex = i % lorem.length
  descriptions.push(lorem[loremIndex])
}

const prices = [
  10.0,
  30.0,
  25.0,
  30.0,
  40.0,
  1000.0,
  1000.0,
  1000.0,
  2000.0,
  80.0,
  100.0,
  40.0,
  110.0,
  15.0,
  45.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  100.0,
  150.0,
  150.0,
  150.0,
  50.0,
  50.0,
  50.0,
  10.0,
  60.0,
]

const quantities = [
  9,
  5,
  2,
  4,
  7,
  1,
  1,
  1,
  1,
  4,
  2,
  20,
  15,
  50,
  37,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  75,
  75,
  75,
  75,
  75,
  75,
  75,
  75,
]

const imageUrls = [
  'https://www.anthem-sports.com/media/extendware/ewimageopt/media/inline/b0/c/bison-pro-tech-competition-breakaway-basketball-goal-ba35--eeb.jpg',
  'https://cdn.vox-cdn.com/thumbor/Ck7EIuSSZBpSn7QIkFZHpAhGuS0=/26x136:1026x803/1200x800/filters:focal(26x136:1026x803)/cdn.vox-cdn.com/uploads/chorus_image/image/30673345/speedflex_quarter_view_lr__2_.0.jpg',
  'https://images-na.ssl-images-amazon.com/images/I/91pq68EoDsL._AC_SL1500_.jpg',
  'https://dks.scene7.com/is/image/GolfGalaxy/16WILUJTVLTNXXXXXBKB?qlt=70&wid=600&fmt=pjpeg',
  'https://target.scene7.com/is/image/Target/GUEST_6c6b3561-8fbb-4019-8e2d-7a7eb00ee749?wid=325&hei=325&qlt=80&fmt=webp',
  'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1966.png',
  'https://images-na.ssl-images-amazon.com/images/I/61hzuoXwjqL._AC_SX466_.jpg',
  'https://images-na.ssl-images-amazon.com/images/I/71E41MppXjL._AC_SX425_.jpg',
  'https://cdn.shopify.com/s/files/1/1171/4980/products/product-base-plate-mounted-football-goals.jpg?v=1527185390',
  'https://www.staples-3p.com/s7/is/image/Staples/m001440649_sc7?wid=512&hei=512',
  'https://images-na.ssl-images-amazon.com/images/I/51Rw3wtCOYL._AC_SL1333_.jpg',
  'https://www.rockler.com/media/catalog/product/cache/e4d64343b1bc593f1c5348fe05efa4a6/4/4/44073-02-1000.jpg',
  'https://dks.scene7.com/is/image/GolfGalaxy/19NIKAPG3TBBLKWHTMNK_Black_White?qlt=70&wid=600&fmt=pjpeg',
  'https://images-na.ssl-images-amazon.com/images/I/81wVGXSD3TL._AC_SX425_.jpg',
  'https://i.ebayimg.com/images/g/6WMAAOSweqdeWrmV/s-l640.jpg',
  'https://fanatics.frgimages.com/FFImage/thumb.aspx?i=/productimages/_2867000/ff_2867430c_full.jpg&w=600',
  'https://images-na.ssl-images-amazon.com/images/I/81Hzq+uvE0L._AC_SS300_.jpg',
  'https://fanatics.frgimages.com/FFImage/thumb.aspx?i=/productimages/_2509000/ff_2509008c_full.jpg&w=600',
  'https://fanatics.frgimages.com/FFImage/thumb.aspx?i=/productimages/_3633000/altimages/ff_3633451-cc2eaf57b9854d908de7alt2_full.jpg&w=600',
  'https://fanatics.frgimages.com/FFImage/thumb.aspx?i=/productimages/_2709000/altimages/ff_2709494alt2_full.jpg&w=600',
  'https://cdn11.bigcommerce.com/s-b0wguna27q/images/stencil/500x659/products/921/727/KembaGreenSwingman550a__64164.1569600706.jpg?c=2',
  'https://cdn11.bigcommerce.com/s-1ah1x75lfn/images/stencil/original/products/5020/28513/040619_thumb__88538.1585078063.jpg?c=2',
  'https://cdn11.bigcommerce.com/s-1nrqf/images/stencil/1280x1280/products/156420/271118/New_York_Yankees_Big_Tall_Replica_Home_Jersey_by_Nike2_2__91304.1579562366.jpg?c=2&imbypass=on',
  'https://cdn2.bigcommerce.com/server2700/18e00/products/5757/images/15993/7700_RSXH__41730.1459373888.1280.1280.jpg?c=2',
  'https://clevelandsportsshop.com/wp-content/uploads/2017/02/LeBron-James-Cleveland-Cavaliers-adidas-Player-Swingman-Jersey-Navy.jpg',
  'https://d2lhrgc5rek5ye.cloudfront.net/pub/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/e/d/ed7387_image.jpg',
  'https://dks.scene7.com/is/image/GolfGalaxy/18ADIMCSJVWHTHMRNJUV?qlt=70&wid=600&fmt=pjpeg',
  'https://images-na.ssl-images-amazon.com/images/I/61cVMSzSiLL._AC_UL1000_.jpg',
  'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productimages/_2399000/ff_2399624_full.jpg&w=900',
  'https://cdn.shopify.com/s/files/1/0906/5342/products/NickLight_SoccerBall1.jpg?v=1497386076',
  'https://cdn3.volusion.com/goz35.avhz4/v/vspfiles/photos/SM-NIAJ3541-109-2.jpg?v-cache=1553159867',
  'https://www.soccerpro.com/wp-content/uploads/sp0040_101_nike_j_guards_01.jpg',
  'https://images-na.ssl-images-amazon.com/images/I/71mLGvbq28L._AC_SL1500_.jpg',
  'https://i1.wp.com/hookedonsoccer.com/wp-content/uploads/2013/08/p-674-real-madrid-away-13_14.jpg?fit=800%2C800',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSs_5HYAzbSAvjvx0aW1k_l9Lb4jUSVY7xm978RgO1kG1ApDDE5&usqp=CAU',
  'https://images-na.ssl-images-amazon.com/images/I/61zjj2sgXML._SL1500_.jpg',
  'https://images-na.ssl-images-amazon.com/images/I/315zvYgE%2BtL.jpg',
  'https://cdn02.nintendo-europe.com/media/images/10_share_images/support_9/H2x1_NSwitch_support_no_logo.jpg',
  'https://images-na.ssl-images-amazon.com/images/I/41LO2OX6pRL._SX342_.jpg',
  'https://images-na.ssl-images-amazon.com/images/I/41Q5bkJP37L._SR600,315_SCLZZZZZZZ_.jpg',
  'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5748/5748618_sd.jpg',
  'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6359/6359364_sd.jpg',
  'https://media.gamestop.com/i/gamestop/11094749/Call-of-Duty-Modern-Warfare?$pdp$',
]

const sports = [
  'basketball',
  'football',
  'football',
  'basketball',
  'baseball',
  'basketball',
  'gaming',
  'basketball',
  'football',
  'gaming',
  'baseball',
  'baseball',
  'basketball',
  'gaming',
  'football',
  'football',
  'football',
  'football',
  'basketball',
  'basketball',
  'basketball',
  'baseball',
  'baseball',
  'baseball',
  'basketball',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'soccer',
  'gaming',
  'gaming',
  'gaming',
  'gaming',
  'gaming',
  'gaming',
  'gaming',
  'gaming',
]

module.exports = {
  names,
  prices,
  quantities,
  imageUrls,
  sports,
  descriptions,
}
